# Generated by Django 4.2.6 on 2023-10-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='data.model'),
        ),
    ]
