# Generated by Django 4.2.6 on 2023-11-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_product_model_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.AddField(
            model_name='model',
            name='categories',
            field=models.ManyToManyField(blank=True, to='data.category'),
        ),
        migrations.AddField(
            model_name='model',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
    ]
