# Generated by Django 4.2.6 on 2023-11-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_faq_model_scheme_modelfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена'),
        ),
    ]
