# Generated by Django 4.2.6 on 2023-11-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_model_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order_num',), 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='old_id',
        ),
        migrations.AddField(
            model_name='category',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='category',
            name='order_num',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
