# Generated by Django 4.2.6 on 2023-11-12 17:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_category_options_remove_category_old_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ('order_num',), 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Название alt'),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_alt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='description_alt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание_alt'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Название alt'),
        ),
        migrations.AddField(
            model_name='model',
            name='order_num',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='price_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена_alt'),
        ),
        migrations.AddField(
            model_name='model',
            name='short_description_alt',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание_alt'),
        ),
        migrations.AddField(
            model_name='modelfeature',
            name='label_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Название_alt'),
        ),
        migrations.AddField(
            model_name='modelfeature',
            name='value_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение_alt'),
        ),
        migrations.AddField(
            model_name='modeltab',
            name='label_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Название таба_alt'),
        ),
        migrations.AddField(
            model_name='modeltab',
            name='text_alt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст_alt'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_alt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст_alt'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Название_alt'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='label_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Название_alt'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение_alt'),
        ),
    ]
