# Generated by Django 4.2.6 on 2023-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_product_options_product_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_at_equipment',
            field=models.BooleanField(default=False, verbose_name='Вывод на странице equipment ?'),
        ),
    ]
