# Generated by Django 5.0.3 on 2024-04-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_category_show_at_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, null=True, upload_to='forms', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CallbackForm',
                'verbose_name_plural': 'CallbackForms',
            },
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('firm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фирма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RequestForm',
                'verbose_name_plural': 'RequestForm',
            },
        ),
    ]
