# Generated by Django 5.0.3 on 2024-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_callbackform_requestform'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='tag_description',
            field=models.TextField(blank=True, null=True, verbose_name='Тег description EN'),
        ),
        migrations.AddField(
            model_name='model',
            name='tag_description_alt',
            field=models.TextField(blank=True, null=True, verbose_name='Тег description DE'),
        ),
        migrations.AddField(
            model_name='model',
            name='tag_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег title EN'),
        ),
        migrations.AddField(
            model_name='model',
            name='tag_title_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег title DE'),
        ),
    ]
